<%@ Page Title="" Language="C#" MasterPageFile="~/Visitor.master" AutoEventWireup="true" CodeFile="FAQ.aspx.cs" Inherits="FAQ" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="auto-style10">
        <tr>
            <td>
                <h2 style="box-sizing: border-box; letter-spacing: -0.02em; margin: 0px 0px 20px; padding: 0px; font-size: 50px; line-height: 52px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">New Delhi NCR – FAQs</h2>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">What is AhaarINN&nbsp;Eats?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    AhaarINN&nbsp;Eats is our new food delivery platform that makes getting great food from your favorite local restaurants as easy as requesting a ride.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">When is AhaarINN&nbsp;Eats available?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    AhaarINN&nbsp;Eats is available from 10:00 AM – 11:00 PM, seven days a week.</p>
                <h4 id="coverage" style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Where is AhaarINN&nbsp;Eats available?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    AhaarINN&nbsp;Eats is currently available throughout most of the Gurugram area. Specific neighborhoods in our coverage zone include Cyber City, Golf course Road, DLF Phase 4, Sohna Road, South City, Sector 14 and Sector 29. Pop open the app to see what&#39;s available in your area.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">How do I start using AhaarINN&nbsp;Eats?</h4>
                <ol class="list" style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px 0px 0px 40px; list-style: decimal outside !important; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Open AhaarINN on your browser.</li>
                    <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Choose from the full menu of New Delhi NCR’s best restaurants.</li>
                    <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Place your order and follow along as your meal is prepared and delivered!</li>
                </ol>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">How much does AhaarINN&nbsp;Eats cost?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    The delivery fee for AhaarINN&nbsp;Eats is a flat Rs 25.</p>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Note that prices and offers on the AhaarINN&nbsp;Eats website and in the AhaarINN&nbsp;Eats app may differ from prices and offers in the restaurant.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">What is the delivery fee on AhaarINN&nbsp;Eats?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    The delivery fee on AhaarINN&nbsp;Eats is a charge you pay to AhaarINN on every delivery that helps to cover operational costs.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">How do you select restaurants?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    We’ve partnered with top restaurants in New Delhi NCR to bring their menus to AhaarINN&nbsp;Eats.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">What if I have food allergies or want to change the order?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    For most meals that you order through AhaarINN&nbsp;Eats, you’ll be able to add special instructions to let restaurants know about any modifications you may need.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">What if I have a problem with my order?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    We’re here to help. Once you’ve placed an order, just contact our support team from within the app and we’ll take care of your issue.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Will my delivery partner bring the meal to my door or inside my office?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Your delivery partner will bring your order right to your door. If it&#39;s easiest for you to walk outside—that&#39;s fine too. You can always meet the delivery partner at the curb.</p>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Do I need to tip my delivery partner?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Tips aren&#39;t included and they aren&#39;t expected or required. You can rate your experience each time you order - just like you rate an AhaarINN ride.</p>
                <div id="promo-codes" style="box-sizing: border-box; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0);">How do promo codes and credits work?</h4>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        <strong style="box-sizing: border-box; font-weight: 700; color: rgb(0, 0, 0);">PROMO CODES</strong></p>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        AhaarINN offers special promotions to provide discounts on food to Eaters. If you have added multiple promo codes to your account, you&#39;ll be unable to select your preferred promo code from your account. Instead, your most recently added promo code will be applied to your current or next order. For example, if you added a valid code on Tuesday and another code on Wednesday, your next order will use the code you added on Wednesday. A promo code&#39;s value will only apply to one order. Any remaining amount disappears.</p>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        <strong style="box-sizing: border-box; font-weight: 700; color: rgb(0, 0, 0);">ADD A PROMO CODE TO YOUR ACCOUNT</strong></p>
                    <ol class="list" style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px 0px 0px 40px; list-style: decimal outside !important;">
                        <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Tap the profile icon at the bottom of the main screen.</li>
                        <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Tap &quot;Promotions&quot;</li>
                        <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Tap &quot;Enter Promo Code&quot;</li>
                        <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Enter the code and tap &quot;Apply&quot;</li>
                    </ol>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        <strong style="box-sizing: border-box; font-weight: 700; color: rgb(0, 0, 0);">VIEW ACTIVE, REDEEMED, AND EXPIRED PROMO CODES ON YOUR ACCOUNT</strong></p>
                    <ol class="list" style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px 0px 0px 40px; list-style: decimal outside !important;">
                        <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Tap the profile icon at the bottom of the main screen.</li>
                        <li style="box-sizing: border-box; margin-bottom: 0px; padding-left: 5px;">Tap &quot;Promotions&quot;</li>
                    </ol>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        <strong style="box-sizing: border-box; font-weight: 700; color: rgb(0, 0, 0);">CREDITS</strong></p>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        AhaarINN credits can be applied to any order. To use them, all you need to do is tap &quot;CREDITS&quot; next to your account&#39;s payment method at check out. This will bring up your payments profile, where you can use the toggle to apply AhaarINN credits to future orders. To check your credits balance, tap the profile icon at the bottom of the main screen and tap &quot;Payment&quot; to see your credit balance.</p>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        You can also share your personal invite code with friends to earn credits. Select profile icon at the bottom of the main screen. Then tap &quot;Free Food&quot; from the menu to view your invite code. When a friend orders their first meal with AhaarINN&nbsp;Eats, your account will receive AhaarINN credits. The amount of AhaarINN credits for a referral will vary by city.</p>
                    <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0);">Where do I find my personal AhaarINN&nbsp;Eats promo code?</h4>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        You can find your AhaarINN&nbsp;Eats promo code by opening the AhaarINN&nbsp;Eats app, tapping on the profile icon at the bottom right, and then tapping on &quot;free food.&quot;</p>
                    <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0);">How do I share my code and get the discount?</h4>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        You can use the share buttons on the &quot;free food&quot; page, or copy/paste the text onto emails, social media or anywhere else. When a friend makes an order using your code you will receive the discount.</p>
                    <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0);">Can I apply the discount to rides in the AhaarINN app?</h4>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        Sorry, AhaarINN&nbsp;Eats discounts are for AhaarINN&nbsp;Eats orders only.</p>
                    <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0);">Does the discount apply in other cities?</h4>
                    <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em;">
                        The discount is valid in AhaarINN&nbsp;Eats cities that have the same currency. If you travel to a country with a different currency, the discount will not apply.</p>
                </div>
                <h4 style="box-sizing: border-box; margin: 0px 0px 20px; padding: 0px; font-size: 24px; line-height: 30px; font-family: &quot;AhaarINN Move&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-weight: 700; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">I’m a restaurant and am interested in partnering with AhaarINN&nbsp;Eats. How do I get more information?</h4>
                <p style="box-sizing: border-box; margin: 24px 0px; padding: 0px; letter-spacing: 0.005em; color: rgb(113, 113, 113); font-family: &quot;AhaarINN Move Text&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    Thanks for your interest! We’re always looking to deliver great new dishes. Please start by<span>&nbsp;</span><a href="Registration3.aspx" style="box-sizing: border-box; background: 0px 0px; color: rgb(79, 147, 0); text-decoration: none; cursor: pointer; font-weight: 700;">filling out this form</a>.</p>
            </td>
        </tr>
    </table>
</asp:Content>

